spring.application.name=telegram-bot
telegram.bot.token=8247976420:AAHW9Wu_EFwEP_xcHSAhti_rGfDlNJSdwvo
telegram.chat.id=@BOnlinediscount

google.sheet.id=1z3U5J2qDkRhXQ8muPtPazF0a_bSiX7fYVDO9uVUSlM0
google.sheet.range=Sheet1!A2:F

instagram.access-token=EAAPYjux20jkBSLqsy33mjXzKeEJCOBi6qZBF40nxfZAEyyB2ukDhTDZCUP7PKLFNJeqZAgOrqmOfxutxiiJqDyVIZBW9fgtbZCvezWphXmdb0Xk0jZCUP0UO4qvabX1VxYS2g1KG6gw8UhnGEbbkUSa4VmZCiPstJyxAJWtp14Uzf4INwjT9qfE6zZAIhlGgqsYkoJRYLKgOCYHp8j2lFhVkpRZC1ZAZAcutPmTlbjFwugJWgrLrcrkzi46XfCEtv9MZA3fb0bhGcWJpipgvQrbr9UIaa6nMmzDnPG0SQpAZDZD
instagram.business-id=17841409837583820